name: JumpCreator
version: 1.0.0
author: Etrenak
main: fr.etrenak.jumpcreator.JumpCreator

commands:
  CreateJump:
    aliases: ["CJ"]
  RemoveJump:
    aliases: ["RmJump", "RJ"]
  JDebug:
  